### ISSUE TITLE
Jellyfin on TV needs server version 10.9 flatpak only has 10.8

### ISSUE THREAD

**Issue by gopikrishnansa** [flathub/org.jellyfin.JellyfinServer#282]
Jellyfin on TV requires server version 10.9, but the Flatpak only has version 10.8. There is a constant warning message on the Jellyfin TV app indicating that, from the next version onwards, version 10.8 will not be able to run on the TV app. Please update it.

**Comment by gopikrishnansa** [comment]
Please look in to it.

**Comment by parx01** [comment]
@wjt  in the link you provided, post is marked closed as “not planned”. Does it mean the community team which was looking after flathub version of jellyfin is not doing so anymore? Should we look for alternate options?  is there is no possibility for it to be updated?

**Comment by wjt** [comment]
No, it means that flathub-infra/flatpak-external-data-checker#432 was filed against the wrong repository. The maintainers of that tool are not responsible for keeping apps updated.

**Comment by oharaandrew314** [comment]
I don't know if the maintainer will keep this up to date any longer.

For those on debian based distributions, Jellyfin has an official repository that makes it easy to stay up to date.  Just make sure you stop and uninstall the flatpack before you install the new version.  You will, unfortunately, need to reconfigure your server

```bash
$ curl -s https://repo.jellyfin.org/install-debuntu.sh | sudo bash
```

**Comment by lwbt** [comment]
After a couple of hours I got it working. I forked the manifest, inspected every component and updated it whenever possible. Try and error, try and error, try and error... and now it works and I have some clean up to do before I push the changes to the public.

I can't promise that you will be getting an updated version of Jellyfin from Flathub soon. That's up to the maintainers to decide (decisions made when choosing dependencies, mistakes I have not discovered yet, eventually code smell). But in theory, the Flatpak is not dead and those who dare to install flatpak-builder and follow the instructions I'm going to write should be able to build it themselves and test it after 30 to 45 minutes of compiling.

**Comment by vmazi** [comment]
howdy! anyway to maybe release this as a new project on flathub?

**Comment by lwbt** [comment]
> howdy! anyway to maybe release this as a new project on flathub?,

As far as I understand, and what I have seen in other projects, operators of Flathub want to avoid a sprawl of apps that are all the same but packaged by different people. There can only be one Jellyfin Server Flatpak. istori1 went through an approval process which also required acknowledgement from the Jellyfin project lead that this Flatpak can be published. It's also not my intention to create a fork. If there are difficulties in maintaining the Flatpak then I'd rather like to step up as a maintainer. But that requires some more time for me to get familiar with the topic.

> howdy! anyway to maybe release this as a new project on flathub?, I tried building and i keep getting a `/tmp/tmpgwa_hv_p/.venv/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'multidict._multilib' is absent from the`packages`configuration`

You need to provide full details of what you are doing before I can help you. Starting somewhere in the middle is very time consuming.

- Which instructions are you trying to follow? [These?](https://github.com/lwbt/org.jellyfin.JellyfinServer/tree/pr-update-to-v10.9-messy)
- Which operating system do you use? I use Ubuntu LTS 24.04. I checked it on a clean machine and did not run into any noteworthy issues, but I cannot rule out that I made a mistake somewhere of forgot to write something down.
- Have you installed `pipx` and then ran `pipx install poetry`?
- Try to use an AI assistant like Gemini or ChatGPT. When you provide them the details I just asked for, they usually give some useful answers that bring you a step further.

One of the next things on my list was to investigate how to build re-distributable Flatpaks so that I would be able to eventually share them with people who have difficulties building them themselves.

**Comment by wjt** [comment]
Ensure the latest PR to update the app is tested and builds correctly, then contact the Flathub admins, asking to adopt the app

**Comment by gopikrishnansa** [comment]
Thanks for all the work guys. I waited so long and was directly copy pasting movies on my TV to watch. So today I thought I can try to manually install jellyfin and followed the official documentation. It wasn't as hard as I thought. I setup jellyfin manually. Those who are still stuck here because of the lack of flatpak support should try the official documentation. Jellyfiin provides a bash script and it was very easy. You only have to paste this comment

curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash

**Comment by lwbt** [comment]
That's good for you, but some people run different distributions than Ubuntu or Debian. Some of those different distributions primarily support Flatpak.

**Comment by lwbt** [comment]
I managed to create Flatpak bundles today for x86_64 and ARM64. Until the current issues are solved or until I can work around them by myself you can find the link to the bundles in https://github.com/flathub/org.jellyfin.JellyfinServer/issues/359.

I hope we can get some feedback. If the situation remains unchanged as it has been for some time now, I will contact Flathub admins according to the documentation.

**Comment by lwbt** [comment]
I received permissions for this repository today and was able to push out the latest 10.09 build. 10.10 will be released soon.

```
$ curl -s https://flathub.org/apps/org.jellyfin.JellyfinServer | html2markdown | grep Changes
### Changes in version 10.9.11
```
